name: virexa_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^8.2.1
  http: ^1.2.2
  intl: ^0.20.3
  web_socket_channel: ^3.0.3
  shared_preferences: 2.3.5
  audioplayers: ^6.8.1
  record: ^7.1.1
  flutter_pcm_sound: ^3.3.3
  flutter_tts: ^4.2.5

dependency_overrides:
  record_android:
    path: third_party/record_android
  flutter_pcm_sound:
    path: third_party/flutter_pcm_sound
  path_provider_foundation: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
